export const frontendUrls = {
    STUDENT_REGISTRATION: '/student-registration/',
    INSTRUCTOR_REGISTRATION: '/instructor-registration/',
    COURSES: '/courses',
    dashboard: {
        DASHBOARD: '/dashboard-2-2',
        MY_PROFILE: '/dashboard-2-2/my-profile/',
        ENROLLED_COURSES: '/dashboard-2-2/enrolled-courses/',
        WISHLIST: '/dashboard-2-2/wishlist',
        REVIEWS: '/dashboard-2-2/reviews/',
        MY_QUIZ_ATTEMPTS: '/dashboard-2-2/my-quiz-attempts/',
        ORDER_HISTORY: '/dashboard-2-2/purchase_history/',
        QUESTION_AND_ANSWER: '/dashboard-2-2/question-answer/',
        CALENDER: '/dashboard-2-2/calendar/',
        MY_COURSES: '/dashboard-2-2/my-courses/',
        MY_BUNDLES: '/dashboard-2-2/my-bundles/',
        ANNOUNCEMENTS: '/dashboard-2-2/announcements/',
        WITHDRAWS: '/dashboard-2-2/withdraw/',
        QUIZ_ATTEMPTS: '/dashboard-2-2/quiz-attempts/',
        GOOGLE_MEET: '/dashboard-2-2/google-meet/',
        ASSIGNMENTS: '/dashboard-2-2/assignments/',
        ZOOM: '/dashboard-2-2/zoom/',
        CERTIFICATE: '/dashboard-2-2/certificate-builder/',
        ANALYTICS: '/dashboard-2-2/analytics/',
        SETTINGS: '/dashboard-2-2/settings/',
        LOGOUT: '/dashboard-2-2/logout',
    }
}

export const backendUrls = {
    LOGIN: 'wp-login.php',
    COURSE_BUNDLES: 'wp-admin/admin.php?page=course-bundle',
    CATEGORIES: 'wp-admin/edit-tags.php?taxonomy=course-category&post_type=courses',
    TAGS: 'wp-admin/edit-tags.php?taxonomy=course-tag&post_type=courses',
    STUDENTS:'wp-admin/admin.php?page=tutor-students',
    INSTRUCTORS: 'wp-admin/admin.php?page=tutor-instructors',
    ANNOUNCEMENTS: 'wp-admin/admin.php?page=tutor_announcements',
    QUESTION_AND_ANSWER: 'wp-admin/admin.php?page=question_answer',
    QUIZ_ATTEMPTS: 'wp-admin/admin.php?page=tutor_quiz_attempts',
    ASSIGNMENTS: 'wp-admin/admin.php?page=tutor-assignments',
    COURSES:"wp-admin/admin.php?page=tutor",
    SETTINGS:"wp-admin/admin.php?page=tutor_settings",
    SETTINGS_COURSE:"wp-admin/admin.php?page=tutor_settings&tab_page=course",
    ENROLLMENTS:"wp-admin/admin.php?page=enrollments",
    WITHDRAW_REQUESTS:"wp-admin/admin.php?page=tutor_withdraw_requests",
    GOOGLE_CLASSROOM:"wp-admin/admin.php?page=tutor-google-classroom",
    GOOGLE_MEET:"wp-admin/admin.php?page=google-meet",
    ZOOM:"wp-admin/admin.php?page=tutor_zoom",
    REPORTS:"wp-admin/admin.php?page=tutor_report",
    GRADEBOOK:"wp-admin/admin.php?page=tutor_gradebook"
}
