const dashboardUrl = process.env.CYPRESS_dashboard_url || '/dashboard';

export const frontendUrls = {
  STUDENT_REGISTRATION: process.env.CYPRESS_student_registration_url || '/student-registration',
  INSTRUCTOR_REGISTRATION: process.env.CYPRESS_instructor_registration_url || '/instructor-registration',
  COURSES: process.env.CYPRESS_course_archive_url || '/courses',
  dashboard: {
    DASHBOARD: dashboardUrl,
    MY_PROFILE: `${dashboardUrl}/my-profile/`,
    ENROLLED_COURSES: `${dashboardUrl}/courses?tab=enrolled`,
    WISHLIST: `${dashboardUrl}/wishlist/`,
    REVIEWS: `${dashboardUrl}/reviews/`,
    MY_QUIZ_ATTEMPTS: `${dashboardUrl}/my-quiz-attempts/`,
    ORDER_HISTORY: `${dashboardUrl}/purchase_history/`,
    QUESTION_AND_ANSWER: `${dashboardUrl}/question-answer/`,
    CALENDAR: `${dashboardUrl}/calendar/`,
    MY_COURSES: `${dashboardUrl}/my-courses/`,
    ANNOUNCEMENTS: `${dashboardUrl}/announcements/`,
    WITHDRAWS: `${dashboardUrl}/withdraw/`,
    QUIZ_ATTEMPTS: `${dashboardUrl}/quiz-attempts/`,
    GOOGLE_MEET: `${dashboardUrl}/google-meet/`,
    ASSIGNMENTS: `${dashboardUrl}/assignments/`,
    ZOOM: `${dashboardUrl}/zoom/`,
    CERTIFICATE: `${dashboardUrl}/certificate-builder/`,
    ANALYTICS: `${dashboardUrl}/analytics/`,
    SETTINGS: `${dashboardUrl}/settings/`,
    LOGOUT: `${dashboardUrl}/logout/`,
  },
  WOOCOMMERCE_CART: process.env.CYPRESS_woo_cart_url || '/woo-cart',
  WOOCOMMERCE_CHECKOUT: process.env.CYPRESS_woo_checkout_url || '/woo-checkout',
  TUTOR_CART: process.env.CYPRESS_tutor_cart_url || '/cart',
  TUTOR_CHECKOUT: process.env.CYPRESS_tutor_checkout_url || '/checkout',
};

export const backendUrls = {
  LOGIN: '/wp-login.php',
  AJAX_URL: '/wp-admin/admin-ajax.php',
  COUPONS: '/wp-admin/admin.php?page=tutor_coupons',
  COURSE_BUNDLES: '/wp-admin/admin.php?page=course-bundle',
  CATEGORIES: '/wp-admin/edit-tags.php?taxonomy=course-category&post_type=courses',
  TAGS: '/wp-admin/edit-tags.php?taxonomy=course-tag&post_type=courses',
  STUDENTS: '/wp-admin/admin.php?page=tutor-students',
  INSTRUCTORS: '/wp-admin/admin.php?page=tutor-instructors',
  ANNOUNCEMENTS: '/wp-admin/admin.php?page=tutor_announcements',
  QUESTION_AND_ANSWER: '/wp-admin/admin.php?page=question_answer',
  QUIZ_ATTEMPTS: '/wp-admin/admin.php?page=tutor_quiz_attempts',
  ASSIGNMENTS: '/wp-admin/admin.php?page=tutor-assignments',
  COURSES: '/wp-admin/admin.php?page=tutor',
  SETTINGS: '/wp-admin/admin.php?page=tutor_settings',
  SETTINGS_COURSE: '/wp-admin/admin.php?page=tutor_settings&tab_page=course',
  ENROLLMENTS: '/wp-admin/admin.php?page=enrollments',
  WITHDRAW_REQUESTS: '/wp-admin/admin.php?page=tutor_withdraw_requests',
  GOOGLE_CLASSROOM: '/wp-admin/admin.php?page=tutor-google-classroom',
  GOOGLE_MEET: '/wp-admin/admin.php?page=google-meet',
  ZOOM: '/wp-admin/admin.php?page=tutor_zoom',
  REPORTS: '/wp-admin/admin.php?page=tutor_report',
  GRADEBOOK: '/wp-admin/admin.php?page=tutor_gradebook',
  WOOCOMMERCE_ORDERS: '/wp-admin/admin.php?page=wc-orders',
  ORDERS: '/wp-admin/admin.php?page=tutor_orders',
  COURSE_BUILDER: '/wp-admin/admin.php?page=create-course&course_id=',
  CONTENT_BANK: '/wp-admin/admin.php?page=tutor-content-bank',
};
