export const TUTOR_CUSTOM_EVENTS = {
  TAB_CHANGE: 'tutor-tab-change',
  MODAL_OPEN: 'tutor-modal-open',
  MODAL_UPDATE: 'tutor-modal-update',
  MODAL_CLOSE: 'tutor-modal-close',
  TOAST_SHOW: 'tutor-toast-show',
  TOAST_CLEAR: 'tutor-toast-clear',
  FORM_REGISTER: 'tutor-form-register',
  FORM_UNREGISTER: 'tutor-form-unregister',
  FORM_STATE_CHANGE: 'tutor-form-state-change',
  TUTOR_PLAYER_READY: 'tutor-player-ready',
  COMMENT_REPLIED: 'tutor:comment:replied',
  LESSON_PLAYER_READY: 'tutorLessonPlayerReady',
  QUIZ_TIME_EXPIRED: 'tutor-quiz-time-expired',
  QUIZ_ABANDON_REQUESTED: 'tutor-quiz-abandon-requested',
};
