const endpoints = {
  APP_CONFIG: 'store.appConfig',
  CATEGORIES: 'store.categories',
  CATEGORY_BY_ID: 'store.categoryById',
  TAGS: 'store.tags',
  CREATE_TAG: 'store.createQuickTag',
  PRODUCE_IMAGES: 'store.images',
  CLEAR_TEMPORARY_IMAGES: 'store.clearTemporaryImages',
  PRODUCTS: 'store.products',
  PRODUCTS_WITH_VARIANTS: 'store.productsWithVariants',
  PRODUCT_BY_ID: 'store.productById',
  PRODUCTS_BY_CATEGORY: 'store.productsByCategory',
  PRODUCTS_EXCEPT_CATEGORY: 'store.productsExceptCategory',
  COUPONS: 'store.coupons',
  DUPLICATE_COUPON: 'store.duplicateCoupon',
  ASSIGN_TO_PRODUCTS: 'store.assignToProducts',
  TAG_BY_ID: 'store.tagById',
  SETTINGS: 'store.settings',
  PRODUCT_IMAGE_ORDERING: 'store.imageOrdering',
  COUPON_BY_ID: 'store.couponById',
  GIFT_CARDS: 'store.giftCards',
  COUPON_BULK_EDIT: 'store.couponBulkEdit',
  ORDERS: 'store.orders',
  ORDER_BY_ID: 'store.orderById',
  VALIDATE_COUPON_CODE: 'store.validateCoupon',
  USERS: 'store.users',
  USER_BY_ID: 'store.userById',
};

export default endpoints;
