const defaultTutorConfig = {
  ID: 0,
  ajaxurl: '',
  site_url: '',
  home_url: '',
  site_title: '',
  base_path: '',
  tutor_url: '',
  tutor_pro_url: '',
  dashboard_url: '',
  nonce_key: '',
  _tutor_nonce: '',
  loading_icon_url: '',
  placeholder_img_src: '',
  enable_lesson_classic_editor: '',
  tutor_frontend_dashboard_url: '',
  backend_course_list_url: '',
  backend_bundle_list_url: '',
  frontend_course_list_url: '',
  frontend_bundle_list_url: '',
  wp_date_format: '',
  wp_rest_nonce: '',
  is_admin: '',
  is_admin_bar_showing: '',
  max_upload_size: '',
  content_change_event: '',
  is_tutor_course_edit: '',
  assignment_max_file_allowed: '',
  current_page: '',
  quiz_answer_display_time: '',
  is_ssl: '',
  course_list_page_url: '',
  course_post_type: '',
  local: '',
  difficulty_levels: [],
  supported_video_sources: [],
  edd_products: [],
  bp_groups: [],
  timezones: {},
  addons_data: [],
  current_user: {
    data: {
      id: '',
      user_login: '',
      user_pass: '',
      user_nicename: '',
      user_email: '',
      user_url: '',
      user_registered: '',
      user_activation_key: '',
      user_status: '',
      display_name: '',
    },
    caps: {},
    cap_key: '',
    roles: [],
    allcaps: {},
    filter: null,
  },
  settings: {
    monetize_by: __TUTOR_TEXT_DOMAIN__,
    enable_course_marketplace: 'off',
    course_permalink_base: '',
    supported_video_sources: '',
    enrollment_expiry_enabled: 'off',
    enable_q_and_a_on_course: 'off',
    instructor_can_delete_course: 'off',
    instructor_can_change_course_author: 'off',
    instructor_can_manage_co_instructors: 'off',
    chatgpt_enable: 'off',
    course_builder_logo_url: '',
    chatgpt_key_exist: false,
    hide_admin_bar_for_users: 'off',
    enable_redirect_on_course_publish_from_frontend: 'off',
    instructor_can_publish_course: 'off',
    youtube_api_key_exist: false,
    membership_only_mode: false,
    enable_tax: false,
    enable_individual_tax_control: false,
    is_tax_included_in_price: false,
  },
  tutor_currency: {
    symbol: '',
    currency: '',
    position: '',
    thousand_separator: '',
    decimal_separator: '',
    no_of_decimal: '',
  },
  visibility_control: {
    course_builder: {},
  },
};

export const tutorConfig = window._tutorobject || defaultTutorConfig;
window.ajaxurl = tutorConfig.ajaxurl;

const config = {
  TUTOR_SITE_URL: tutorConfig.site_url,
  WP_AJAX_BASE_URL: tutorConfig.ajaxurl,
  WP_API_BASE_URL: `${window.wpApiSettings?.root || ''}${window.wpApiSettings?.versionString || ''}`,
  VIDEO_SOURCES_SETTINGS_URL: `${tutorConfig.site_url}/wp-admin/admin.php?page=tutor_settings&tab_page=course#field_supported_video_sources`,
  MONETIZATION_SETTINGS_URL: `${tutorConfig.site_url}/wp-admin/admin.php?page=tutor_settings&tab_page=monetization`,
  TUTOR_PRICING_PAGE: 'https://tutorlms.com/pricing/',
  TUTOR_ADDONS_PAGE: `${tutorConfig.site_url}/wp-admin/admin.php?page=tutor-addons`,
  CHATGPT_PLATFORM_URL: 'https://platform.openai.com/account/api-keys',
  TUTOR_MY_COURSES_PAGE_URL: `${tutorConfig.tutor_frontend_dashboard_url}/my-courses`,
  TUTOR_SUPPORT_PAGE_URL: 'https://tutorlms.com/support',
  TUTOR_SUBSCRIPTIONS_PAGE: `${tutorConfig.site_url}/wp-admin/admin.php?page=tutor-subscriptions`,
  TUTOR_ENROLLMENTS_PAGE: `${tutorConfig.site_url}/wp-admin/admin.php?page=enrollments`,
  TUTOR_COUPONS_PAGE: `${tutorConfig.site_url}/wp-admin/admin.php?page=tutor_coupons`,
  TUTOR_IMPORT_EXPORT_PAGE: `${tutorConfig.site_url}/wp-admin/admin.php?page=tutor-tools&sub_page=import_export`,
};

export default config;
